name: Deploy Astro Build to Hostinger

on:
  push:
    branches:
      - production # Cette branche déclenche le déploiement, tu peux la modifier si nécessaire

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3


      - name: Install dependencies
        run: npm install

      - name: Build Astro project
        run: npm run build

      - name: Checkout deploy branch
        run: git fetch origin deploy && git checkout deploy

      - name: Remove all files except dist
        run: |
          # Supprime tous les fichiers sauf le dossier dist
          find . -mindepth 1 ! -regex '^./dist\(/.*\)?' -exec rm -rf {} +

      - name: Move build files to deploy branch
        run: |
          # Déplace les fichiers de build dans la branche deploy
          mv dist/* .

      - name: Commit changes
        run: |
          git add .
          git commit -m "Deploy Astro build"
          git push origin deploy --force  # Pousse sur la branche deploy

      - name: Clean dist folder
        run: |
          # Vide le dossier dist à la racine du projet
          rm -rf dist/*
